#list methods
1=[1,2,3,4,5,77]
1.appen(89)
print("appen.1")
1.sort(reverse=True)
print("sort",1)
1.pop(1)
print("remove by position is pop")
a=1.copy()
print("copy",a)
b=1.count(1)
print("count of 1",b)
a=["ss","hh","hh"]
1.extend(S)
print("extend".1)
c=1.index("hh")
print("index",c)
1.insert(1,"sss")
print("insert",1)
1.remove("hh")
print("remove",1)
1.reverse()
print("reverse",1)
1.clear()
print("clear",1)
#string method
m="meena"
x=s.capitalize()
print("upper case",x)
s=x.casefold()
print("lower case",s)
s=s.center(10,"s")
m="i am mee"
m=m.count("am")
print(s)
ss=ss.endswith("m")
print(ss)
s="a good girl"
mm=s.find("s")
print(mm)
a=s.replace("a","an")
print(a)